### ISSUE TITLE
Escape codes to resize text area are not supported

### ISSUE THREAD

**Issue by ejuarezg** [giusgad/pets.nvim#1]
Hi!

I'm trying to get the plugin working and when I run `PetsNew first`, I see the following error thrown by kitty: `Escape codes to resize text area are not supported`. Moreover, nvim starts consuming all of my RAM until is it killed by the system.

Any input on why this may be happening is appreciated.

**Comment by giusgad** [comment]
I'm not sure why that is happening and am unable to reproduce, my only idea is to try updating your neovim and kitty and see if that helps

**Comment by ejuarezg** [comment]
I apologize for the trouble. I managed to figure out what the root of the issue was.

I'm running neovim on Fedora Silverblue inside a container. I'm guessing terminal programs like neovim have issues when running in a container. I don't have an idea what the exact issue is but at least I know it happens when running in a container.

I did not encounter the issue when running neovim natively outside a container.

Closing as this issue is unrelated to your plugin.
