### ISSUE TITLE
Pets render much higher over the status line than what is seen on the preview

### ISSUE THREAD

**Issue by DaneParcJr** [giusgad/pets.nvim#16]
I'm using a customized lazyvim configuration if that helps. But on the lowest row, 0. The pets render much higher in the viewport than what I saw in the preview. Is this intentional, and can we lower it to above the status line?

![image](https://user-images.githubusercontent.com/45432721/220426237-ac9ce106-c613-495b-ba8f-4f9d3c260999.png)

**Comment by giusgad** [comment]
Have you tried adjusting the `row` option to something like 4 or 5? Note that higher `row` value means the pet gets rendered lower on the screen.

**Comment by DaneParcJr** [comment]
I'll close this. I thought that 0 was the lowest row, bleh, my mistake.
