### ISSUE TITLE
Pets crash when switching or opening a new tab

### ISSUE THREAD

**Issue by EvanKoe** [giusgad/pets.nvim#19]
OS: Debian 12,
Term: Kitty,
Nvim version: 0.9.0-dev-213+gcc5b7368d

What happened: 
I create a new cat with `:PetsNew cat`, a cat appears on the screen. Then, I create a new tab with `:tabnew` (or `C-t`), and the extension crashes : 
![image](https://user-images.githubusercontent.com/72010109/220905151-e327a2c8-1cb2-4ee3-9b61-521c94ab29ff.png)
(The cat stands without animation as soon as it crashes).

It's also the same behaviour when `gt`/`gT` to switch between already opened tabs.

Atm, I'm forced to `:PetsHideToggle` before switching to another tab.

I don't know if it's a Pets or a Hologram limitation. 
Does anyone had faced the same issue ?

Thanks !

**Comment by giusgad** [comment]
This is related to #17, which I might have just fixed with a drawback, when errors such as this occur pets get hidden, and you have to manually un-hide them using the `:PetsHideToggle` command. I will have to find a better solution that doesn't require user interaction.

**Comment by giusgad** [comment]
It should be fixed now! Please let me know if the issue persists for you :)

**Comment by kawaegle** [comment]
@giusgad It seem fixed for me, but when I suspend my nvim session with CTRL+z the cat dispawn and I can't recreate the cat because the name is already in use

**Comment by giusgad** [comment]
@kawaegle I tried looking into the <C-z> issue but it doesn't seem to be related to this one. I will close this and open a new one for your problem. Thank you for the feedback!
