### ISSUE TITLE
Breaks with hologram auto_display = true

### ISSUE THREAD

**Issue by matthewsia98** [giusgad/pets.nvim#3]
```
Error executing vim.schedule lua callback: ...ocal/share/nvim/lazy/hologram.nvim/lua/hologram/init.lua:47: Invalid buffer id: 3
stack traceback:
	[C]: in function 'nvim_buf_get_extmarks'
	...ocal/share/nvim/lazy/hologram.nvim/lua/hologram/init.lua:47: in function 'buf_render_images'
	...ocal/share/nvim/lazy/hologram.nvim/lua/hologram/init.lua:17: in function <...ocal/share/nvim/lazy/hologram.nvim/lua/hologram/init.lua:17>
Error executing vim.schedule lua callback: ...ocal/share/nvim/lazy/hologram.nvim/lua/hologram/init.lua:47: Invalid buffer id: 4
stack traceback:
	[C]: in function 'nvim_buf_get_extmarks'
	...ocal/share/nvim/lazy/hologram.nvim/lua/hologram/init.lua:47: in function 'buf_render_images'
	...ocal/share/nvim/lazy/hologram.nvim/lua/hologram/init.lua:17: in function <...ocal/share/nvim/lazy/hologram.nvim/lua/hologram/init.lua:17>
E492: Not an editor command: Mes
Error executing vim.schedule lua callback: ...ocal/share/nvim/lazy/hologram.nvim/lua/hologram/init.lua:47: Invalid buffer id: 500
stack traceback:
	[C]: in function 'nvim_buf_get_extmarks'
	...ocal/share/nvim/lazy/hologram.nvim/lua/hologram/init.lua:47: in function 'buf_render_images'
	...ocal/share/nvim/lazy/hologram.nvim/lua/hologram/init.lua:17: in function <...ocal/share/nvim/lazy/hologram.nvim/lua/hologram/init.lua:17>
Error executing vim.schedule lua callback: ...ocal/share/nvim/lazy/hologram.nvim/lua/hologram/init.lua:47: Invalid buffer id: 499
stack traceback:
	[C]: in function 'nvim_buf_get_extmarks'
	...ocal/share/nvim/lazy/hologram.nvim/lua/hologram/init.lua:47: in function 'buf_render_images'
	...ocal/share/nvim/lazy/hologram.nvim/lua/hologram/init.lua:17: in function <...ocal/share/nvim/lazy/hologram.nvim/lua/hologram/init.lua:17>
```

**Comment by giusgad** [comment]
From my understanding, there is nothing I can do about this inside my plugin, because it is related to how hologram displays its images. What I found is that every image that I create using hologram's API is counted as an image from hologram, and so it tries to treat it as if it was a normal image displayed in a markdown file. To fix this I should then change a part of hologram, which I'm not sure if I can do. Any advice is appreciated.

**Comment by matthewsia98** [comment]
Looks like there is a [PR](https://github.com/edluffy/hologram.nvim/pull/26) open for this on hologram, but project doesn't seem active

**Comment by giusgad** [comment]
I guess that since the maintainer doesn't seem active, we could either switch to the fork from the person that created PR you mentioned, or create a new one with the fix applied. Do you have any suggestion on which option might be best?

**Comment by matthewsia98** [comment]
I think this project should maintain its own fork of hologram

**Comment by matthewsia98** [comment]
Not erroring out anymore
![image](https://user-images.githubusercontent.com/71731492/221307887-bdd41a27-6768-4e5b-8ce9-e792aca741e3.png)

However, once I scroll down
![image](https://user-images.githubusercontent.com/71731492/221308078-4a6a154d-7639-45a7-b1a4-d0715ae7bf92.png)

Not a priority to fix though

**Comment by giusgad** [comment]
I opened #29 for your new issue, thank you!
