### ISSUE TITLE
How to interact with pets?

### ISSUE THREAD

**Issue by sangdth** [giusgad/pets.nvim#31]
### Description

I would like to know a way to interact with them, like feed them, pet them etc

### Your options

```Lua
Calling function is fine too. For example:


require("pets").actions.feed()
```
```


### Screenshots

_No response_

### Extra

Thank you <3

**Comment by giusgad** [comment]
This would be cool, but every pet would need a new animation where they do the interactive action. So I fear that it would not be easy to implement, as I don't really have the time to create a new animation for every pet. Vscode pets' pets that I use have a “with ball” animation, so I guess I could do something with that, even tough I would have to add pseudo physics for the ball. So if anything I will add the ball throwing interaction, but I'm not sure I ever will.
Thank you for your suggestion :)

**Comment by sangdth** [comment]
Thanks for response. I don't use kitty terminal but downloaded it today just to test this plugin, and I love it!

For the animation, I would say keep it simple, the physics sound cool but it's too much for this simple project, so I think something like `sit()`, `roll()`, `run()` with pure animations could be enough.

If you could point me into your implementation, I might spend some free time on weekend to try a PR.

What do you think?

**Comment by giusgad** [comment]
Okay, this is how it would work:
First of all, the pets don't have the animations for sit or roll, they only have a `with_ball` animation where they are holding the ball. So when the `PetsThrowBall` command gets called it spawns a boll (let's say on the left side of the screen) and it rolls until it meets the pet. When it does, the pet switches into the with ball animation and the ball disappears. The pet then holds it for a second or two, and then it keeps on doing its thing.
The ball is an object, similar to the `Pet` object, and for the animation uses either a custom function only for it or the same animation class used for pets. I think that implementing the ball that just stays on the same row and reaches the pet moving left to right is fair enough for now, we'll improve that later.
The `PetsThrowBall` command should probably take an argument `name` of the pet, so the ball gets thrown at a specific pet and ignores the others.
If you have any doubt feel free to reach out. If you decide to not try the PR tell me and I will implement this on my own in the next couple of weeks at most, makes no difference to me as I already have a rough idea, so choose freely :). If on the other hand, you want to try it, open a draft PR (add some comment or blank line if you can't open it with no changes) and I will add the animations for the `pets_with_ball`, and the assets for the ball itself.
Note that the ball will only be available for the pets I took from vscode pets, if this works out I will manually create the art for the other ones (which are dog and slime).

**Comment by sangdth** [comment]
Thanks @giusgad for detailed comment. I want to sharpen my lua, and the next weekend I will have more free time, I will try to start something simple first. I will ask you more often on the PR so it has better context.

Thanks again. Have a nice day.
