### ISSUE TITLE
Potential Cat Assets

### ISSUE THREAD

**Issue by DaneParcJr** [giusgad/pets.nvim#33]
Came across this asset pack while perusing itch.io. Would it looks like they'd be great for this project and have permissions that should be fine for this project. It's also free.

https://pop-shop-packs.itch.io/cats-pixel-asset-pack

**Comment by giusgad** [comment]
Looks good, I think I'll go ahead and ask the author just to be sure and we'll see from there. Thank you for the suggestion :)

**Comment by DaneParcJr** [comment]
:) Hopefully it works out!

**Comment by giusgad** [comment]
The author prefers to not have the assets available on other sites, so we won't be able to use them. If you still want to set them up locally for yourself I can help you, just let me know.
