### ISSUE TITLE
Installed pets.vim but can't start it.

### ISSUE THREAD

**Issue by bschroedr** [giusgad/pets.nvim#34]
### Description

I have installed pets.vim with the dependencies under lazy vim (in lunarvim) and I can see that the plugins have installed. However, when I try to find the plugin at. ":" nothing is available for PetsNew, etc.  When I check the plugin status for pets.vim, it is installed and has the text "> start" next to it.

### Steps to reproduce

1. start lvim
2. type :PetStart
3. not available (e.g. even with :P - tab.

### Your options

```Lua
I don't have any options set with

require("pets").setup()

as I don't know what they should be.
```

### Extra

I am running this using iTerm on a Mac.

**Comment by giusgad** [comment]
First of all, as is stated in the plugin's README, it only works inside the kitty terminal emulator, so if you're using iTerm you won't be able to use it. In any case, if you were to still face this issue in case you switched terminal, it is most likely related to how you use lazy.nvim, you may try to set `lazy=false` for the plugin and see if the commands pop up (`PetStart` is not a command, you can see the available ones in the README). You can read more about how to set up plugins in the lazy.nvim docs or in the lunarvim ones.

**Comment by bschroedr** [comment]
Ok, as a new user, I wasn't completely sure what that meant. So maybe in the future, you can be a bit more cognizant that might be the case and not come across as being snide, understand it could be a point of error.

**Comment by giusgad** [comment]
I was not being disrespectful, I told you where you can read to solve your issue. Reading documentation is really important to understand how the tools you use work. Your problem is not related to my plugin but to your configuration, so I tried pointing you in the right direction to solve it.
