### ISSUE TITLE
Where is the cat?

### ISSUE THREAD

**Issue by t1gu1** [giusgad/pets.nvim#35]
### Description

Cat does seems to exist anymore.

But it already exist and it was my favorite.
https://preview.redd.it/f53xpg5oscia1.gif?format=mp4&s=36270cd709bdaf334651f2b74025622ede0ca680

### Steps to reproduce

`PetsNewCustom cat gray catty` and it say that the pet "cat" does not exist. :'(

### Your options

```Lua
{
        row = 7, -- the row (height) to display the pet at (higher row means the pet is lower on the screen), must be 1<=row<=10
        col = 0, -- the column to display the pet at (set to high number to have it stay still on the right side)
        speed_multiplier = 1, -- you can make your pet move faster/slower. If slower the animation will have lower fps.
        default_pet = "dog", -- the pet to use for the PetNew command
        default_style = "gray", -- the style of the pet to use for the PetNew command
        random = true, -- wether to use a random pet for the PetNew command, ovverides default_pet and default_style
        death_animation = true, -- animate the pet's death, set to false to feel less guilt -- currently no animations are available
        popup = { -- popup options, try changing these if you see a rectangle around the pets
          width = "100%", -- can be a string with percentage like "45%" or a number of columns like 45
          winblend = 100, -- winblend value - see :h 'winblend' - only used if avoid_statusline is false
          hl = { Normal = "Normal" }, -- hl is only set if avoid_statusline is true, you can put any hl group instead of "Normal"
          avoid_statusline = false, -- if winblend is 100 then the popup is invisible and covers the statusline, if that
          -- doesn't work for you then set this to true and the popup will use hl and will be spawned above the statusline (hopefully)
        },
      }
```

**Comment by t1gu1** [comment]
Oh, I may use a forked project in the past.
There is the [cats media](https://github.com/Kyle-Mendes/pets.nvim/tree/main/media/cat).

**Comment by t1gu1** [comment]
I open a PR to add cats from the other repo. (They don't seems maintained)

https://github.com/giusgad/pets.nvim/pull/37

**Comment by giusgad** [comment]
The cat assets were removed as explained in #26 due to a licensing problem and are not going to be added back. In the issue I also explain how you can set them up locally but in order to do that you have to buy the assets, if you obtained them from an old fork, you should remove them and buy them if you want to use them. The link is in the credits section of the readme.
