### ISSUE TITLE
Toggle state only applies to pets, so spawning new pets causes a mismatch.

### ISSUE THREAD

**Issue by Kyle-Mendes** [giusgad/pets.nvim#6]
1. :PetsNew a
2. :PetsPauseToggle (1 cat is paused)
3. :PetsNew b

RESULT:
b will be animated with a is not

EXPECTED RESULT:
b and a are paused until you toggle again.

**Comment by giusgad** [comment]
If you want to take care of that that's great! My first idea when creating the commands was to have a PetsHide {name} and PetsHideAll command, that would remove the toggle and we would have double the commands so:
- PetsHideAll
- PetsHide {name}
- PetsShowAll
- PetsShow {name}
- same as above with pause/play
This would remove the problem of toggling and give more control to the user but it would also significantly increase the number of command. Please share what approach you think it's best! Thank you for the help :)
