### ISSUE TITLE
Pink Box still appearing after latest update

### ISSUE THREAD

**Issue by LizAinslie** [giusgad/pets.nvim#8]
While i don't particularly mind the box behind my cat (i like to think of it as a playpen xD) i know you're trying to resolve the issue so here's a screenshot of what i'm seeing

![](https://i-work-at-the.cocaine.institute/Lizzy63ee50d0WjKttNnFg3ej.png)

i'm not getting any errors so i don't know how i can help on that front

**Comment by giusgad** [comment]
Try something like this:
```lua
vim.api.nvim_set_hl(0, "pets_popup", { link = "Normal" })
require("pets").setup({
  popup = {
    avoid_statusline = true,
    hl = { Normal = "pets_popup" },
  },
})
```
This likely won't work, but it should if you replace `link="Normal"` with something like `bg="NONE"` or at worst `bg="#rrggbb"` (replacing `rrggbb` with your values) to set it manually.

**Comment by LizAinslie** [comment]
Got it to work by setting the bg as a hex code 🙏🏻
![](https://i-work-at-the.cocaine.institute/Lizzy63ee9294InOVS0NqFiXD.png)

**Comment by giusgad** [comment]
Great!
